/* Casa Nira · Villa C2 · The Sanctuary — FF&E Upgrade SSOT
 * Source: "UPGRADE SSOT - UPGRADE NEW FORMAT FF&E 3BR.pdf"
 * status: "upgrade" | "new" | "asis"
 * custom: true  -> counts toward the "Custom Branding" tab
 */

const VILLA = {
  brand: "CASA NIRA",
  villa: "VILLA C2",
  owner: "THE SANCTUARY",       // C7 used an owner name here; edit freely
  location: "THE SANCTUARY · ULUWATU",
  docType: "UPGRADE DOC",
  year: "2026",
  updated: "July 2026",
};

const SECTIONS = [
  "Electronics & Appliances",
  "Fixed Furniture",
  "Loose Furniture",
  "Amenities",
  "Cleaning Tools",
];

const INVENTORY = [
  // ── Electronics & Appliances ─────────────────────────────
  { s:"Electronics & Appliances", name:"Smartlock", loc:"Main Entrance", status:"asis", qty:1, old:"Onassis", brand:"", note:"" },
  { s:"Electronics & Appliances", name:'Smart TV 55"', loc:"Living Room", status:"upgrade", qty:1, old:"Samsung Smart TV", brand:"", note:"With Google TV" },
  { s:"Electronics & Appliances", name:'Smart TV 45"', loc:"All Bedrooms", status:"upgrade", qty:3, old:"Samsung Smart TV", brand:"", note:"With Google TV" },
  { s:"Electronics & Appliances", name:"AC Inverter 2 PK", loc:"Living Room", status:"upgrade", qty:1, old:"Gree", brand:"Panasonic", note:"" },
  { s:"Electronics & Appliances", name:"AC Inverter 1.5 PK", loc:"Master Bedroom", status:"upgrade", qty:1, old:"Gree", brand:"Panasonic", note:"" },
  { s:"Electronics & Appliances", name:"AC Inverter 1 PK", loc:"Dining Room, 2nd Bedroom, 3rd Bedroom", status:"upgrade", qty:3, old:"Gree", brand:"Panasonic", note:"" },
  { s:"Electronics & Appliances", name:"Fridge", loc:"Kitchen", status:"asis", qty:1, old:"LG", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Microwave", loc:"Kitchen", status:"upgrade", qty:1, old:"Electrolux", brand:"Modena", note:"Switch brand" },
  { s:"Electronics & Appliances", name:"Oven", loc:"Kitchen", status:"upgrade", qty:1, old:"Electrolux", brand:"Hafele", note:"Switch brand" },
  { s:"Electronics & Appliances", name:"Induction Stove + Downdraft", loc:"Kitchen", status:"upgrade", qty:1, old:"Modena", brand:"Hafele", note:"Switch brand" },
  { s:"Electronics & Appliances", name:"Coffee Machine", loc:"Kitchen", status:"asis", qty:1, old:"Nespresso", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Water Dispenser", loc:"Kitchen", status:"upgrade", qty:1, old:"Modena", brand:"Polytron", note:"With new feature" },
  { s:"Electronics & Appliances", name:"Wifi", loc:"Living Room", status:"upgrade", qty:1, old:"From Provider", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Router", loc:"Living Room", status:"asis", qty:1, old:"TP-Link", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Wifi Access Point", loc:"Master Bedroom, 2nd Floor", status:"asis", qty:2, old:"TP-Link", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Ceiling Fan", loc:"Living Room, Outdoor Dining, All Bedroom", status:"asis", qty:5, old:"Ecolux", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Ceiling Speaker & Amplifier", loc:"Living Room, Dining", status:"upgrade", qty:4, old:"Intelligent Electronics", brand:"Q Acoustics", note:"Premium audio upgrade from Intelligent Electronics to Q Acoustics; audiophile-grade in-ceiling speakers for guest experience" },
  { s:"Electronics & Appliances", name:"Hair Dryer", loc:"All Bedrooms", status:"asis", qty:3, old:"Panasonic", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Water Heater", loc:"All Bedrooms, Kitchen", status:"asis", qty:4, old:"Ariston", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"CCTV", loc:"Villa Entrance", status:"upgrade", qty:1, old:"Ezviz", brand:"Onassis", note:"Brand switch from Ezviz to Onassis; matches smartlock brand for a unified smart-security ecosystem" },
  { s:"Electronics & Appliances", name:"Blender", loc:"Kitchen", status:"asis", qty:1, old:"Philips", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Electric Kettle", loc:"Kitchen", status:"asis", qty:1, old:"Azko", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Iron", loc:"All Bedrooms", status:"asis", qty:3, old:"Philips", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"TV Stand", loc:"All Bedrooms", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Electronics & Appliances", name:"Washer & Dryer Machine", loc:"Laundry Room", status:"asis", qty:1, old:"Modena", brand:"", note:"" },

  // ── Fixed Furniture ──────────────────────────────────────
  { s:"Fixed Furniture", name:"Wall Shelving", loc:"Living Room", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Kitchen Cabinet Set", loc:"Kitchen", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Island", loc:"Kitchen", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Vanity Shelving", loc:"Powder Room, All Bedrooms", status:"asis", qty:5, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Headboard Table + Base", loc:"All Bedrooms", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"TV Cabinet / Shelving", loc:"Living Room, All Bedrooms", status:"asis", qty:4, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Wall Shelving", loc:"All Bedrooms", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Wardrobe", loc:"All Bedrooms", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Vanity Shelving", loc:"All Bedrooms", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Outdoor Sofa", loc:"Rooftop, Outdoor Terrace", status:"asis", qty:2, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Freestanding Bathtub", loc:"Master Bathroom", status:"asis", qty:1, old:"Villo New Zealand Terrazzo Tub", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Bathroom Mirror", loc:"Master Bathroom", status:"upgrade", qty:1, old:"Custom Made", brand:"", note:"New feature: backlit LED behind mirror" },
  { s:"Fixed Furniture", name:"Bathroom Mirror", loc:"2nd Bathroom, 3rd Bathroom", status:"asis", qty:2, old:"Custom Made", brand:"", note:"" },
  { s:"Fixed Furniture", name:"Featured Mirror", loc:"All Bedrooms", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },

  // ── Loose Furniture ──────────────────────────────────────
  { s:"Loose Furniture", name:"Indoor Dining Chair", loc:"Dining", status:"asis", qty:4, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Outdoor Dining Table", loc:"Outdoor Terrace", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Outdoor Dining Chair", loc:"Outdoor Terrace", status:"asis", qty:4, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Sunbed Base", loc:"Outdoor Terrace", status:"asis", qty:2, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Sunbed Mattress", loc:"Outdoor Terrace", status:"asis", qty:2, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Stool (Chair)", loc:"Outdoor Shower", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"TV Credenza", loc:"Living Room", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Sofa Set", loc:"Living Room", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Coffee Table Set", loc:"Living Room", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Lazy Chair", loc:"Living Room, Master Bedroom", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Standing Lamp", loc:"Living Room, Master Bedroom", status:"asis", qty:2, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Paintings", loc:"Living Room, Dining Room, All Bedrooms", status:"asis", qty:6, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Bedroom Mattress", loc:"All Bedrooms", status:"asis", qty:3, old:"Turu", brand:"", note:"" },
  { s:"Loose Furniture", name:"Bed Stool", loc:"Master Bedroom", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Hanging Lamp", loc:"All Bedrooms", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Table Lamp", loc:"Living Room, All Bedrooms", status:"asis", qty:4, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Towel Rack", loc:"Master Bathroom", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Working Chair", loc:"2nd Bedroom, 3rd Bedroom", status:"asis", qty:2, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Surf Rack", loc:"Outdoor Terrace", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Sunbed Portable Table", loc:"Outdoor Terrace", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Bathtub Table Tray", loc:"Master Bedroom", status:"upgrade", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Vases", loc:"Outdoor Terrace, Living Room, Master Bedroom", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Carpet", loc:"Living Room, Bedroom", status:"asis", qty:4, old:"Custom Made / Fio Carpet", brand:"", note:"" },
  { s:"Loose Furniture", name:"Outdoor Coffee Table", loc:"Rooftop", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Loose Furniture", name:"Bathroom Wooden Tray", loc:"Master Bathroom", status:"new", qty:2, old:"", brand:"", note:"New addition for tub-side amenity placement (candles, drink, book)" },
  { s:"Loose Furniture", name:"Living Room Statement Tray", loc:"Living Room", status:"new", qty:1, old:"", brand:"", note:"New decorative coffee-table tray (statement styling piece)" },
  { s:"Loose Furniture", name:"Luggage Holder", loc:"Living Room", status:"new", qty:3, old:"", brand:"", note:"New guest amenity" },

  // ── Amenities ────────────────────────────────────────────
  { s:"Amenities", name:"Curtain", loc:"All Rooms", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Amenities", name:"Sofa Linen", loc:"Living Room", status:"asis", qty:1, old:"Indolinen / Custom Local", brand:"", note:"" },
  { s:"Amenities", name:"Table Flower Vase", loc:"All Rooms", status:"asis", qty:7, old:"Custom Made", brand:"", note:"" },
  { s:"Amenities", name:"Shelving Decor", loc:"All Rooms", status:"asis", qty:4, old:"Custom Made", brand:"", note:"" },
  { s:"Amenities", name:"Tissue Box", loc:"All Rooms", status:"asis", qty:4, old:"Azco", brand:"", note:"" },
  { s:"Amenities", name:"Water Glass", loc:"Kitchen", status:"upgrade", qty:1, old:"Art on the Table", brand:"Sango", note:"" },
  { s:"Amenities", name:"Cutlery Set", loc:"Kitchen", status:"upgrade", qty:1, old:"Art on the Table", brand:"Bolde", note:"" },
  { s:"Amenities", name:"Cooking Pan Set", loc:"Kitchen", status:"upgrade", qty:1, old:"Stein", brand:"Bolde", note:"" },
  { s:"Amenities", name:"Napkin Set", loc:"Kitchen", status:"asis", qty:1, old:"Informa", brand:"", note:"" },
  { s:"Amenities", name:"Pillow Set", loc:"All Bedrooms", status:"upgrade", qty:3, old:"DDPillow", brand:"", note:"" },
  { s:"Amenities", name:"Mattress Linen Set", loc:"All Bedrooms", status:"upgrade", qty:3, old:"Indolinen", brand:"", note:"" },
  { s:"Amenities", name:"Blanket", loc:"All Bedrooms", status:"upgrade", qty:3, old:"Indolinen", brand:"", note:"" },
  { s:"Amenities", name:"Mattress Protector", loc:"All Bedrooms", status:"upgrade", qty:3, old:"Turu Mattress Protector", brand:"", note:"" },
  { s:"Amenities", name:"Bath Towel Set", loc:"All Bathroom", status:"upgrade", qty:3, old:"Terry Palmer Hotelier", brand:"", note:"" },
  { s:"Amenities", name:"Pool Towel", loc:"All Bathroom", status:"upgrade", qty:3, old:"Terry Palmer Hotelier", brand:"Madeem", note:"" },
  { s:"Amenities", name:"Soap & Shampoo Set", loc:"All Bathroom", status:"asis", qty:3, old:"Botanical Essential", brand:"", note:"" },
  { s:"Amenities", name:"Safety Deposit Box", loc:"Master Bedroom", status:"asis", qty:1, old:"Azco", brand:"", note:"" },
  { s:"Amenities", name:"Reed Diffuser", loc:"Living Room, All Bedrooms", status:"asis", qty:4, old:"Custom Made", brand:"", note:"" },
  { s:"Amenities", name:"Pool Cleaning Kit", loc:"Outdoor Shower / Storage", status:"asis", qty:1, old:"Custom Made", brand:"", note:"" },
  { s:"Amenities", name:"Hotel Slippers", loc:"All Bedrooms", status:"asis", qty:3, old:"Custom Made", brand:"", note:"" },
  { s:"Amenities", name:"Scrub Daddy", loc:"Kitchen", status:"asis", qty:4, old:"Scrub Daddy", brand:"", note:"" },
  { s:"Amenities", name:"Trash Can", loc:"Kitchen, All Bedrooms, All Bathrooms", status:"asis", qty:6, old:"Informa", brand:"", note:"" },
  { s:"Amenities", name:"Plates (Large / Main)", loc:"Kitchen", status:"upgrade", qty:4, old:"", brand:"Sango", note:"Upgrade brand" },
  { s:"Amenities", name:"Plates (Small / Side)", loc:"Kitchen", status:"upgrade", qty:4, old:"", brand:"Sango", note:"Upgrade brand" },
  { s:"Amenities", name:"Bowls (Soup / Cereal)", loc:"Kitchen", status:"upgrade", qty:4, old:"", brand:"Sango", note:"Upgrade brand" },
  { s:"Amenities", name:"Bowls (Small / Snack)", loc:"Kitchen", status:"upgrade", qty:4, old:"", brand:"Sango", note:"Upgrade brand" },
  { s:"Amenities", name:"Coffee Mugs / Glasses", loc:"Kitchen", status:"new", qty:4, old:"", brand:"Sango", note:"" },
  { s:"Amenities", name:"Tea Cups & Saucers", loc:"Kitchen", status:"new", qty:4, old:"", brand:"Sango", note:"" },
  { s:"Amenities", name:"Wine Glasses", loc:"Kitchen", status:"new", qty:4, old:"", brand:"Sango", note:"" },
  { s:"Amenities", name:"Champagne Flutes", loc:"Kitchen", status:"new", qty:4, old:"", brand:"Sango", note:"New glassware addition" },
  { s:"Amenities", name:"Chef's Knife Set", loc:"Kitchen", status:"new", qty:1, old:"", brand:"Bolde", note:"New premium knife set" },
  { s:"Amenities", name:"French Press", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"New — complements existing Nespresso coffee machine" },
  { s:"Amenities", name:"Spatula & Cooking Spoon Set", loc:"Kitchen", status:"asis", qty:1, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Big Wood Cutting Board", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Small Wood Cutting Board", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Peeler", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Pitcher / Water Jug", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Corkscrew & Bottle Opener", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Tongs", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Salt & Pepper", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Coaster", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"New: set of coasters with custom branding", custom:true },
  { s:"Amenities", name:"Display Cutleries", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"New display set (countertop utensil holder)" },
  { s:"Amenities", name:"Dishwasher Tray", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"New: spare rack / specialty tray for delicates" },
  { s:"Amenities", name:"Sharpener", loc:"Kitchen", status:"new", qty:1, old:"", brand:"", note:"New knife sharpener; pairs with the Chef's Knife Set" },
  { s:"Amenities", name:"Hand Towel", loc:"All Bathroom", status:"upgrade", qty:4, old:"Terry Palmer Hotelier", brand:"King Koil", note:"" },
  { s:"Amenities", name:"Face Towel", loc:"All Bathroom", status:"upgrade", qty:4, old:"Terry Palmer Hotelier", brand:"King Koil", note:"" },
  { s:"Amenities", name:"Bath Robe", loc:"All Bathroom", status:"new", qty:4, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Flat Sheet", loc:"All Bedrooms", status:"asis", qty:2, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Duvet Cover", loc:"All Bedrooms", status:"asis", qty:2, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Waterproof Mattress Protector", loc:"All Bedrooms", status:"asis", qty:2, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Duvet Insert", loc:"All Bedrooms", status:"asis", qty:2, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Pillow Case", loc:"All Bedrooms", status:"new", qty:4, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Decorative Pillow", loc:"All Bedrooms", status:"new", qty:4, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Fitted Sheet", loc:"All Bedrooms", status:"new", qty:2, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Pillow Microfiber", loc:"All Bedrooms", status:"new", qty:4, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Throw Blanket", loc:"All Bedrooms", status:"new", qty:2, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Coverlet", loc:"All Bedrooms", status:"new", qty:2, old:"", brand:"", note:"" },
  { s:"Amenities", name:"Access Card Holder", loc:"Outdoor", status:"new", qty:6, old:"", brand:"", note:"", custom:true },
  { s:"Amenities", name:"Access Card", loc:"Outdoor", status:"new", qty:6, old:"", brand:"", note:"", custom:true },
  { s:"Amenities", name:"QR Code Template", loc:"Outdoor", status:"new", qty:1, old:"", brand:"", note:"", custom:true },
  { s:"Amenities", name:"Post Card", loc:"All Rooms", status:"new", qty:6, old:"", brand:"", note:"", custom:true },
  { s:"Amenities", name:"Note Pad", loc:"All Rooms", status:"new", qty:6, old:"", brand:"", note:"", custom:true },
  { s:"Amenities", name:"Pen / Pencil", loc:"All Rooms", status:"new", qty:6, old:"", brand:"", note:"", custom:true },
  { s:"Amenities", name:"Hang Tag Sign", loc:"Outdoor", status:"new", qty:1, old:"", brand:"", note:"", custom:true },
  { s:"Amenities", name:"Writing Pads", loc:"All Rooms", status:"new", qty:1, old:"", brand:"", note:"", custom:true },
  { s:"Amenities", name:"Individual Villa Sign", loc:"Outdoor", status:"new", qty:1, old:"", brand:"", note:"", custom:true },

  // ── Cleaning Tools ───────────────────────────────────────
  { s:"Cleaning Tools", name:"Vacuum Cleaner", loc:"Storage", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Cleaning Tools", name:"Broom & Dustpan", loc:"Storage", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Cleaning Tools", name:"Floor Mop & Bucket", loc:"Storage", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Cleaning Tools", name:"Squeegee & Scraper", loc:"Storage", status:"new", qty:1, old:"", brand:"", note:"" },
  { s:"Cleaning Tools", name:"Toilet Brushes", loc:"Storage", status:"new", qty:4, old:"", brand:"", note:"" },
];
